### PR TITLE
Adds OBS_GetMeasureById

### PR DESCRIPTION
**Pull request by ohasselblad**
@talos, could you give this a CR please?

@ethervoid, this is a new (and needed) function for the extension.

`OBS_GetMeasureById(text,text,text,text)` returns `numeric`.

closes https://github.com/CartoDB/observatory-extension/issues/44

cc @CartoDB/research

### CODE REVIEW

**Comment by talos** [comment]
Looks good!  Two comments:

1. It would be nice if it was possible to call without a boundary ID, and have it default to the highest weighted geom column.  I have a few samples of how to do this, or we could pair on it.
2. I might be missing it, but is there code guaranteeing that the most recent timespan would be used if several are available?  It would be good to do some tests of that using the Zillow data, as that's the only truly temporally rich one available atm.

**Comment by ohasselblad** [comment]
Nice idea on 1, will connect with you IRL. For 2, the most recent timespan is taken care of by [_obs_columndata](https://github.com/CartoDB/observatory-extension/blob/dc718ab7d000a3518019eac4a77fc78326e79601/src/pg/sql/40_observatory_utility.sql#L43).

**Comment by ethervoid** [comment]
This will take 2 days to be included. And we have to freeze version so if there is other functions to add tell me now.

**Comment by ohasselblad** [comment]
Ok, we may want to include one or two more functions in this PR. I'll give you an update soon.

**Comment by talos** [comment]
@ethervoid I think it would be best to wait on deploying this one, but move ahead with #97 which is blocking us from getting new data out there.

**Comment by ohasselblad** [comment]
@talos, thinking about this more, by not passing in a boundary id would me that we would have to guess the boundary that is associated with the input geometry reference. Since we can't reliably do that (e.g., zcta vs county geoid), I think return nulls as it currently does is the best behavior.

**Comment by talos** [comment]
True that!  This should be 👍 then.

**Pull request merged**
