### PR TITLE
New docs folder for developer center

### PR DESCRIPTION
**Pull request by csubira**
The new documentation folder (`docs`) is created to meet the requirements of the new developer center.

At the moment, docs folder contains four folders or categories (`guides`, `reference`, `examples` and `support`). To start, each of them is filled with older information (usually contained in `doc` folder and also from the [dataobservatory folder in docs repository](https://github.com/CartoDB/docs/tree/master/_app/_dataobservatory)).

In this first step, using this branch, the new workflow of documentation repository (for importing and displaying content) is going to be tested.

Once validated, the second step is to get your validation @juanignaciosl about content (correcting current information or adding new items)

### CODE REVIEW

**Comment by ethervoid** [comment]
@csubira what is the state of this PR?

**Comment by csubira** [comment]
Regarding the dev-center connexion, it can be merged as soon as you want. 
Just let me know the final branch and the dev-center will be fetching the content from there!

**Comment by ethervoid** [comment]
The branch to be checked is `master`

**Comment by csubira** [comment]
Great! Already changed in dev-center, thanks!

**Pull request merged**
