### PR TITLE
modified license content as per Operations request

### PR DESCRIPTION
**Pull request by csobier**
For [Docs issue#879](https://github.com/CartoDB/docs/issues/879)

@vhamer , please approve.

@talos , I've updated the license content as described in the attached issue. The DO PDF link contains a license page that is slightly different then the public docs page. I just want to make sure we're using one golden source for the content.

### CODE REVIEW

**Comment by talos** [comment]
I've updated the license text on the PDF, which should move to http://data-observatory.s3.amazonaws.com/observatory.pdf .

In the future, changes to the DO catalog should be filed with github.com/cartodb/bigmetadata, since the PDF is generated as part of the ETL/metadata, not as part of the extension.

@csobier I filed a ticket on cartodb-platform (https://github.com/CartoDB/cartodb-platform/issues/2071) to move the catalog PDF, should that be filed with cartodb-docs instead?  Thanks!

**Comment by talos** [comment]
Ah, I see the confusion -- we have a docs page here that isn't really exposed anywhere.  I'd say just open issues on the bigmetadata repo and don't worry so much about the LICENSE here, since it doesn't surface anywhere.  Maybe we should delete it?

**Comment by csobier** [comment]
Actually, the license.md file (as shown in Doc/API.md) shows the list of files from this repo that I am using to generate the live docs), so it is being used for the public docs page.

**Comment by talos** [comment]
Learn something new every day!  Then I guess we should just keep tickets on here and have you tag me.  Hopefully we don't have to change this text too much.

**Comment by csobier** [comment]
V. is out all day, I'm making the executive decision to approve this merge, since I used her text verbatim.

**Comment by vhamer** [comment]
Thank you Christa!

**Pull request merged**
